Working on database project
JonHMChan/flask-app-4 pull request #1
Opened 2020-04-14 15:29 UTC by kristinalustig

2020-04-14 16:58 UTC, kristinalustig commented on data/schema.sql
> +);*/
I originally had types in its own table in this way because I was trying to make allowances for pokemon with multiple types in a non-cludgy way. But I did more research and found that pokemon can only have a maximum of two types, so I rolled it back into the pokemon table with two columns for type 1 and type 2.

2020-04-14 16:58 UTC, kristinalustig commented on data/schema.sql
> +    team_name VARCHAR(50),
I have a question throughout on conventions for VARCHAR length - I read about why (255) is a convention, but when a string is reliably longer or shorter than that (but still variable), what lengths are appropriate to set?

2020-04-14 16:58 UTC, kristinalustig commented on data/schema.sql
> +    poke_id INTEGER PRIMARY KEY,
I saw a lot of examples that used "NOT NULL" a lot and wasn't sure when it was appropriate to include and when not, so I didn't put it anywhere yet.

2020-04-14 17:10 UTC, JonHMChan requested changes
Your overall schema is looking good! Just a few conventions around column naming, being idempotent, and some thoughts on your types table.

2020-04-14 17:10 UTC, JonHMChan commented on data/schema.sql
> +CREATE TABLE teams (
One of the requirements for your `schema.sql` file is that it is "idempotent" - that means that you can run this schema multiple times and the result would be the same without any errors.

You might want to add a conditional here to check if each table hasn't been created yet, and only then create a table. That would make this idempotent.

2020-04-14 17:10 UTC, JonHMChan commented on data/schema.sql
> +CREATE TABLE teams (
For your column names, no need to prefix them: I would remove prefixes like `team_`, `poke_`, etc.

2020-04-14 17:10 UTC, JonHMChan commented on data/schema.sql
> +    poke_name VARCHAR(50),
Consider using `TEXT` instead of `VARCHAR` for your string types. `VARCHAR` is standard in other databases like SQL (you'll see that in  the Stack Overflow code), but `TEXT` is more standard for Postgres.

2020-04-14 17:10 UTC, JonHMChan commented on data/schema.sql
> +    team_id INTEGER REFERENCES teams(team_id),
Good job on adding a foreign key here! As a convention, I would use the entire table you're referencing as the prefix for a foreign key, so `teams_id` for the column name:

```
  teams_id INTEGER REFERENCES teams(id)
```

2020-04-14 17:10 UTC, JonHMChan commented on data/schema.sql
> +    poke_id INTEGER REFERENCES pokemon(poke_id),
Same here: `pokemon_id INTEGER REFERENCES pokemon(id)`

2020-04-14 17:10 UTC, JonHMChan commented on data/schema.sql
> +    poke_type_1 VARCHAR(10),
This is interesting: I actually opted to put types into a separate table:

```
CREATE TABLE types (
    id INTEGER PRIMARY KEY,
    name TEXT
)
```

This is so if you were to change the type's name, add a new type, etc. it'd be easier to change in the table than in all of the rows of your pokemon table. However, this is a design decision around "normalization": reducing redundancy in your data. You've opted to "denormalize" type data and let it stay directly in your pokemon table. There is a tradeoff here: denormalized data is faster to access because you don't need to do a `JOIN`, but you run the risk of things going out of sync. Normalized data is more resilient and consistent, but there's a trade-off in performance.

This is really your call here, but wanted to note this so you understand the concepts. I think you can go either way here.

2020-04-14 17:10 UTC, JonHMChan commented on data/schema.sql
> +);*/
Yep, see my note about about normalization. I think this is a good decision.

2020-04-14 17:10 UTC, JonHMChan commented on data/schema.sql
> +    poke_id INTEGER PRIMARY KEY,
Only when you *know* that something must be required. For example, you could put this in `pokemon.name`. For this exercise, it's not a requirement, but good to know the rule of thumb.

2020-04-14 17:10 UTC, JonHMChan commented on data/schema.sql
> +    team_name VARCHAR(50),
Good question. This really comes down to understanding your data - there isn't a hard and fast rule. I personally like doing neat multiple of 5 or 10 (as you have here). That being said, you could also bypass the question overall and just consider just using `TEXT`: https://stackoverflow.com/questions/4848964/postgresql-difference-between-text-and-varchar-character-varying

2020-04-15 13:58 UTC, kristinalustig commented on data/schema.sql
> +CREATE TABLE teams (
@JonHMChan question about that - I tried to do that initially but name and description are reserved words in SQL. What's the convention for naming a column properly but avoiding use of reserved words?

2020-04-15 14:20 UTC, kristinalustig commented on data/schema.sql
> +    CREATE DATABASE pokedex;
@JonHMChan I read about a few different ways of doing this - some of them were "CREATE DATABASE IF NOT EXISTS" and "CREATE TABLE IF NOT EXISTS" - I also found this way which allowed me to include all of the creation in just one IF, which if it works I think is simpler. Curious to hear your thoughts. (Also, I'm unable to test this at all yet so I'm not even sure if it works!)

2020-04-16 17:01 UTC, JonHMChan requested changes
Excellent work! My remaining comments are around formatting SQL calls, validation, and a few bits about column names and getting IDs. Once you look these over, I think you could try tackling search using SQL if you want more of a challenge :)

2020-04-16 17:01 UTC, JonHMChan commented on api/pokemon.py
> +        """, ('%'+query+'%',))
Bit of a nit, but recommend you indent in the contents of your SQL call for readability:

```
if len(query) > 0:
    cursor.execute("""
        SELECT *
        FROM pokemon
        WHERE _name ILIKE %s;
    """, ('%'+query+'%',))
```

2020-04-16 17:01 UTC, JonHMChan commented on api/pokemon.py
> +        pokemon_to_return.append({'id':p[0],'name':p[1],'image_url':p[3],'types':[p[4],p[5]]})
While this is perfectly fine, you might also be interested in `map()`, given our conversation yesterday about lambdas and anonymous functions: https://www.geeksforgeeks.org/python-map-function/

2020-04-16 17:01 UTC, JonHMChan commented on api/teams.py
> +    cursor.execute("SELECT * FROM teams;")
As a general rule, it's good to avoid using `SELECT *` and actually enumerate the fields you're trying to fetch (e.g. `SELECT id, name, description FROM teams;`. This makes it easier to infer to someone reading your code what fields are going to be represented, especially in a case like this where they are simply ordered sequentially in a tuple (`t[0]` is `id`, `t[1]` is `name`, etc.).

It's also good practice because it's possible for this table to change and a `SELECT *` would get *all* of those columns, even if you know in this particular function you want only certain fields. Overall, enumerating the columns you want in a `SELECT` statement is a good idea.

2020-04-16 17:01 UTC, JonHMChan commented on api/teams.py
> +    """)
You may not need another `SELECT` here to get the `id` you need here: https://stackoverflow.com/questions/5247685/python-postgres-psycopg2-getting-id-of-row-just-inserted

Saves you some extra work :)

2020-04-16 17:01 UTC, JonHMChan commented on api/teams.py
> +        cursor.execute("INSERT INTO team_members (teams_id, pokemon_id, member_level) VALUES (%s, %s, %s)", (teams_id, pokemon['pokemon_id'], pokemon['level']))
Another nit on formatting, I like to break things up by the SQL keywords for readability:

```
cursor.execute("""
    INSERT INTO
        team_members (teams_id, pokemon_id, member_level)
    VALUES
        (%s, %s, %s);
""", (teams_id, pokemon['pokemon_id'], pokemon['level']))
```

2020-04-16 17:01 UTC, JonHMChan commented on api/teams.py
> +    """, (updated_team['name'], updated_team['description'], id))
For formatting, might be useful to consider:

```
cursor.execute("""
    UPDATE teams
    SET
        _name = %s,
        _desc = %s
    WHERE
        id = %s;
""", (updated_team['name'], updated_team['description'], id))
```

2020-04-16 17:01 UTC, JonHMChan commented on api/teams.py
> +            cursor.execute("UPDATE teams SET _desc = %s WHERE id = %s", (patched_team['description'], id))
Can you think of doing this with one SQL call instead of two if they're on the same table? Try that :)

2020-04-16 17:01 UTC, JonHMChan commented on app.py
>  def search():
If you're done with all the basic requirements, tackling search using SQL would be an interesting challenge.

2020-04-16 17:01 UTC, JonHMChan commented on app.py
> +            teams_id = db.fetchone()
Similar as before, you can get the `id` of a newly inserted row without a new `SELECT` call.

2020-04-16 17:01 UTC, JonHMChan commented on app.py
> +            db.execute("INSERT INTO pokemon (id, _name, _desc, image_url, type_1, type_2) VALUES (%s, %s, %s, %s, %s, %s)", (pokemon['id'], pokemon['name'], pokemon['description'], pokemon['image_url
For this query and other long ones, I'd suggest using a multiline string and formatting by separating SQL keywords as I've noted in other comments.

2020-04-16 17:01 UTC, JonHMChan commented on data/schema.sql
> +    _desc TEXT
I actually think it's fine for you to use `name` and `description` here. While `NAME` is a keyword in Postgres, it's not explicitly forbidden in the table as reserved and `DESCRIPTION` is left out: https://www.postgresql.org/docs/8.1/sql-keywords-appendix.html

2020-04-16 17:01 UTC, JonHMChan commented on data/schema.sql
> +    evol_to TEXT
I would change these column names to avoid the self-referential prefix if they're not using a foreign key. In this case, I would add a foreign key to `evol_id` as well and only use the prefix then:

```
CREATE TABLE IF NOT EXISTS evolutions (
    pokemon_id INTEGER REFERENCES pokemon(id),
    evolution_id INTEGER REFERENCES pokemon(id),
    method TEXT,
    level INTEGER,
    to TEXT
);
```

The reason for this is when others may use your table and column name in a query, you can avoid redundancies:

```
SELECT 
    pokemon.id,
    evolution.evol_method,
    evolution.evol_level,
    evolution.evol_to
FROM
    pokemon
JOIN
    evolutions
ON
    pokemon.id = evolution.pokemon_id
WHERE
    pokemon.id = 1;
```

Your table name is generally already a "prefix" and is generally useful when you have similar column names in the *same* table (like `pokemon_id` and `evolution_id` in this case), and/or when referencing a foreign key like `pokemon_id`.

2020-04-16 17:01 UTC, JonHMChan commented on api/teams.py
>  @teams.route('/teams', methods=['POST'])
For `POST`, `PUT`, and `PATCH` I would consider adding validation. Any time you make an `UPDATE` or `INSERT` operation, doing some validation is a good idea.

2020-10-07 13:15 UTC, closed without merging